-- CreateTable
CREATE TABLE "Client" (
    "code_clt" SERIAL NOT NULL,
    "nom" TEXT NOT NULL,
    "compte" TEXT NOT NULL,
    "tel" TEXT,
    "adresse" TEXT,
    "ville" TEXT NOT NULL,
    "code_region" INTEGER,
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "echeance" INTEGER NOT NULL,
    "mode_paie" TEXT,
    "REMISE_G" DOUBLE PRECISION NOT NULL,
    "bloquer" BOOLEAN NOT NULL DEFAULT false,
    "plafond" DOUBLE PRECISION NOT NULL,
    "code_com" INTEGER NOT NULL,
    "cond_paie" INTEGER,
    "mode_liv" TEXT,
    "code_cat" INTEGER,
    "SOLDE" INTEGER NOT NULL,

    CONSTRAINT "Client_pkey" PRIMARY KEY ("code_clt")
);

-- CreateTable
CREATE TABLE "Comercial" (
    "code_com" SERIAL NOT NULL,
    "nom" TEXT NOT NULL,
    "tel" TEXT,
    "email" TEXT,

    CONSTRAINT "Comercial_pkey" PRIMARY KEY ("code_com")
);

-- CreateTable
CREATE TABLE "Article" (
    "id" SERIAL NOT NULL,
    "code_art" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3),
    "nom" TEXT NOT NULL,
    "desc" TEXT,
    "photo" TEXT,
    "UAF" INTEGER,
    "PA_HT" DOUBLE PRECISION NOT NULL,
    "TVA" DOUBLE PRECISION NOT NULL,
    "PA_TTC" DOUBLE PRECISION NOT NULL,
    "PV_HT" DOUBLE PRECISION NOT NULL,
    "PV_TTC" DOUBLE PRECISION NOT NULL,
    "Code_fam" INTEGER,
    "code_sfam" INTEGER,
    "STK_MAX" INTEGER NOT NULL,
    "STK_MIN" INTEGER NOT NULL,
    "STK_SEC" INTEGER,
    "UVC" INTEGER,
    "REMISEMAX" DOUBLE PRECISION,
    "REF_OEM" TEXT,
    "VENTE_BLOQ" BOOLEAN NOT NULL DEFAULT false,
    "ACHAT_BLOQ" BOOLEAN NOT NULL DEFAULT false,
    "TRANS_BLOQ" BOOLEAN NOT NULL DEFAULT false,
    "LIQUIDER" BOOLEAN NOT NULL DEFAULT false,
    "code_frs" TEXT NOT NULL,
    "familleCode_fam" INTEGER,
    "qte_stk" INTEGER NOT NULL,

    CONSTRAINT "Article_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "famille" (
    "code_fam" INTEGER NOT NULL,
    "nom" TEXT NOT NULL,

    CONSTRAINT "famille_pkey" PRIMARY KEY ("code_fam")
);

-- CreateTable
CREATE TABLE "sfamille" (
    "code_sfam" INTEGER NOT NULL,
    "nom" TEXT NOT NULL,
    "code_fam" INTEGER NOT NULL,

    CONSTRAINT "sfamille_pkey" PRIMARY KEY ("code_sfam")
);

-- CreateTable
CREATE TABLE "Fournisseur" (
    "code_frs" TEXT NOT NULL,
    "compte" TEXT,
    "sociale" TEXT NOT NULL,
    "desc" TEXT,
    "pays" TEXT,
    "echeance" BOOLEAN NOT NULL,
    "note" TEXT,
    "cond_paie" BOOLEAN NOT NULL,
    "bloquer" BOOLEAN NOT NULL,

    CONSTRAINT "Fournisseur_pkey" PRIMARY KEY ("code_frs")
);

-- CreateTable
CREATE TABLE "Devis" (
    "REF_DEV" TEXT NOT NULL,
    "id" SERIAL NOT NULL,
    "DATEVALID" TIMESTAMP(3),
    "DATE_DEV" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "COMPTE" TEXT,
    "CODE_CLT" INTEGER NOT NULL,
    "CLIENT" TEXT NOT NULL,
    "MNT_HT" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "MNT_TTC" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "REMISEG" DOUBLE PRECISION,
    "CODE_COM" INTEGER NOT NULL,
    "VALIDER" BOOLEAN NOT NULL DEFAULT false,
    "REMARQUE" TEXT,
    "MODELIV" TEXT NOT NULL,
    "MODE_PAIE" TEXT NOT NULL,
    "NOTES" TEXT,

    CONSTRAINT "Devis_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DevisDetail" (
    "REF_DEV" TEXT NOT NULL,
    "CODE_ART" TEXT NOT NULL,
    "ARTICLE" TEXT NOT NULL,
    "QTE" DOUBLE PRECISION NOT NULL,
    "GRATUIT" DOUBLE PRECISION,
    "PA_HT" DOUBLE PRECISION NOT NULL,
    "PV_HT" DOUBLE PRECISION NOT NULL,
    "PV_TTC" DOUBLE PRECISION NOT NULL,
    "REMISE" DOUBLE PRECISION NOT NULL,
    "TVA" INTEGER NOT NULL,
    "TotalHT" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "TotalTTC" DOUBLE PRECISION NOT NULL DEFAULT 0,

    CONSTRAINT "DevisDetail_pkey" PRIMARY KEY ("REF_DEV","CODE_ART")
);

-- CreateTable
CREATE TABLE "Bonliv" (
    "REF_BL" TEXT NOT NULL,
    "DATEVALID" TIMESTAMP(3) NOT NULL,
    "HEUREVALID" TIMESTAMP(3),
    "REF_DEV" TEXT NOT NULL,
    "DATE_BL" TIMESTAMP(3) NOT NULL,
    "COMPTE" TEXT,
    "CODE_CLT" INTEGER NOT NULL,
    "CLIENT" TEXT NOT NULL,
    "MNT_HT" DOUBLE PRECISION NOT NULL,
    "MNT_TTC" DOUBLE PRECISION NOT NULL,
    "EN_FACTURE" BOOLEAN NOT NULL,
    "VALIDER" BOOLEAN NOT NULL,
    "MODELIV" TEXT,
    "MODE_PAIE" TEXT,
    "REMARQUE" TEXT,
    "CODE_CON" INTEGER,
    "CODE_ADR" INTEGER,
    "BASEHT" BOOLEAN,
    "IMPRIMER" BOOLEAN,

    CONSTRAINT "Bonliv_pkey" PRIMARY KEY ("REF_BL")
);

-- CreateTable
CREATE TABLE "DetailBonliv" (
    "REF_BL" TEXT NOT NULL,
    "CODE_ART" TEXT NOT NULL,
    "ARTICLE" TEXT NOT NULL,
    "QTECMD" DOUBLE PRECISION NOT NULL,
    "QTEGRA" DOUBLE PRECISION,
    "qteliv" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "QTE" DOUBLE PRECISION NOT NULL,
    "QTECTRL" DOUBLE PRECISION NOT NULL,
    "GRATUIT" DOUBLE PRECISION,
    "PA_HT" DOUBLE PRECISION NOT NULL,
    "PV_HT" DOUBLE PRECISION NOT NULL,
    "PV_TTC" DOUBLE PRECISION NOT NULL,
    "REMISE" DOUBLE PRECISION NOT NULL,
    "REMISEG" DOUBLE PRECISION,
    "TVA" INTEGER NOT NULL,

    CONSTRAINT "DetailBonliv_pkey" PRIMARY KEY ("REF_BL")
);

-- CreateTable
CREATE TABLE "Facture" (
    "REF_FAC" TEXT NOT NULL,
    "DATEVALID" TIMESTAMP(3) NOT NULL,
    "HEUREVALID" TIMESTAMP(3),
    "REF_BL" TEXT NOT NULL,
    "DATE_FAC" TIMESTAMP(3) NOT NULL,
    "COMPTE" TEXT,
    "CODE_CLT" INTEGER NOT NULL,
    "CLIENT" TEXT NOT NULL,
    "MNT_HT" DOUBLE PRECISION NOT NULL,
    "MNT_TTC" DOUBLE PRECISION NOT NULL,
    "CODE_COM" INTEGER NOT NULL,
    "MODELIV" TEXT,
    "MODE_PAIE" TEXT,
    "MNT_DEV" DOUBLE PRECISION,
    "REMARQUE" TEXT,
    "BASEHT" BOOLEAN,
    "VALIDER" BOOLEAN NOT NULL,
    "IMPRIMER" BOOLEAN,

    CONSTRAINT "Facture_pkey" PRIMARY KEY ("REF_FAC")
);

-- CreateTable
CREATE TABLE "DetailFacture" (
    "REF_FAC" TEXT NOT NULL,
    "CODE_ART" TEXT NOT NULL,
    "ARTICLE" TEXT NOT NULL,
    "QTE" DOUBLE PRECISION NOT NULL,
    "GRATUIT" DOUBLE PRECISION,
    "PA_HT" DOUBLE PRECISION NOT NULL,
    "PV_HT" DOUBLE PRECISION NOT NULL,
    "PV_TTC" DOUBLE PRECISION NOT NULL,
    "PD_HT" DOUBLE PRECISION,
    "REMISE" DOUBLE PRECISION NOT NULL,
    "REMISEG" DOUBLE PRECISION,
    "TVA" INTEGER NOT NULL,

    CONSTRAINT "DetailFacture_pkey" PRIMARY KEY ("REF_FAC")
);

-- CreateTable
CREATE TABLE "Avoirs" (
    "REF_AVR" TEXT NOT NULL,
    "DATEVALID" TIMESTAMP(3) NOT NULL,
    "HEUREVALID" TIMESTAMP(3),
    "DATE_AVR" TIMESTAMP(3) NOT NULL,
    "COMPTE" TEXT,
    "CODE_CLT" INTEGER NOT NULL,
    "CLIENT" TEXT NOT NULL,
    "MNT_HT" DOUBLE PRECISION NOT NULL,
    "MNT_TTC" DOUBLE PRECISION NOT NULL,
    "VALIDER" BOOLEAN NOT NULL,
    "CODE_COM" INTEGER NOT NULL,
    "REMARQUE" TEXT,
    "BASEHT" BOOLEAN,
    "code_clt" INTEGER,

    CONSTRAINT "Avoirs_pkey" PRIMARY KEY ("REF_AVR")
);

-- CreateTable
CREATE TABLE "Detailavoirs" (
    "REF_AVR" TEXT NOT NULL,
    "CODE_ART" TEXT NOT NULL,
    "ARTICLE" TEXT NOT NULL,
    "QTE" DOUBLE PRECISION NOT NULL,
    "GRATUIT" DOUBLE PRECISION,
    "PV_HT" DOUBLE PRECISION NOT NULL,
    "PV_TTC" DOUBLE PRECISION NOT NULL,
    "PA_HT" DOUBLE PRECISION NOT NULL,
    "REMISE" DOUBLE PRECISION NOT NULL,
    "REMISEG" DOUBLE PRECISION,
    "TVA" INTEGER NOT NULL,
    "MAJ_STK" BOOLEAN NOT NULL,

    CONSTRAINT "Detailavoirs_pkey" PRIMARY KEY ("REF_AVR")
);

-- CreateTable
CREATE TABLE "Reglement" (
    "REF_REGV" TEXT NOT NULL,
    "DATEVALID" TIMESTAMP(3) NOT NULL,
    "HEUREVALID" TIMESTAMP(3),
    "CODE_CLT" INTEGER NOT NULL,
    "CLIENT" TEXT NOT NULL,
    "DATE_REM" TIMESTAMP(3),
    "DATE_ECH" TIMESTAMP(3),
    "DATE_PNT" TIMESTAMP(3),
    "MODE_REG" TEXT NOT NULL,
    "MNT_REGLER" DOUBLE PRECISION NOT NULL,
    "BANQUE" TEXT,
    "IMPAYER" DOUBLE PRECISION,
    "CPT_BNQ" INTEGER,
    "REMARQUE" TEXT,
    "TIRER" TEXT,
    "VILLE" TEXT,
    "DATE_REG" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Reglement_pkey" PRIMARY KEY ("REF_REGV")
);

-- CreateTable
CREATE TABLE "ReglementDetail" (
    "REF_REGV" TEXT NOT NULL,
    "REF_AV_FAC" TEXT NOT NULL,
    "DATE_DOC" TIMESTAMP(3) NOT NULL,
    "MNT_ORIGINAL" DOUBLE PRECISION NOT NULL,
    "MNT_REGLER" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "ReglementDetail_pkey" PRIMARY KEY ("REF_REGV")
);

-- CreateTable
CREATE TABLE "UnifiedFactureAvoir" (
    "REF_AV_FAC" TEXT NOT NULL,
    "DATE_DOC" TIMESTAMP(3) NOT NULL,
    "MNT_TTC" DOUBLE PRECISION NOT NULL,
    "MNT_REGLER" DOUBLE PRECISION NOT NULL,
    "code_clt" INTEGER NOT NULL,

    CONSTRAINT "UnifiedFactureAvoir_pkey" PRIMARY KEY ("REF_AV_FAC")
);

-- CreateIndex
CREATE UNIQUE INDEX "Article_code_art_key" ON "Article"("code_art");

-- CreateIndex
CREATE UNIQUE INDEX "Devis_REF_DEV_key" ON "Devis"("REF_DEV");

-- AddForeignKey
ALTER TABLE "Client" ADD CONSTRAINT "Client_code_com_fkey" FOREIGN KEY ("code_com") REFERENCES "Comercial"("code_com") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Article" ADD CONSTRAINT "Article_code_frs_fkey" FOREIGN KEY ("code_frs") REFERENCES "Fournisseur"("code_frs") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Article" ADD CONSTRAINT "Article_familleCode_fam_fkey" FOREIGN KEY ("familleCode_fam") REFERENCES "famille"("code_fam") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sfamille" ADD CONSTRAINT "sfamille_code_fam_fkey" FOREIGN KEY ("code_fam") REFERENCES "famille"("code_fam") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Devis" ADD CONSTRAINT "Devis_CODE_CLT_fkey" FOREIGN KEY ("CODE_CLT") REFERENCES "Client"("code_clt") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Devis" ADD CONSTRAINT "Devis_CODE_COM_fkey" FOREIGN KEY ("CODE_COM") REFERENCES "Comercial"("code_com") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DevisDetail" ADD CONSTRAINT "DevisDetail_CODE_ART_fkey" FOREIGN KEY ("CODE_ART") REFERENCES "Article"("code_art") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DevisDetail" ADD CONSTRAINT "DevisDetail_REF_DEV_fkey" FOREIGN KEY ("REF_DEV") REFERENCES "Devis"("REF_DEV") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Bonliv" ADD CONSTRAINT "Bonliv_CODE_CLT_fkey" FOREIGN KEY ("CODE_CLT") REFERENCES "Client"("code_clt") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DetailBonliv" ADD CONSTRAINT "DetailBonliv_CODE_ART_fkey" FOREIGN KEY ("CODE_ART") REFERENCES "Article"("code_art") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DetailBonliv" ADD CONSTRAINT "DetailBonliv_REF_BL_fkey" FOREIGN KEY ("REF_BL") REFERENCES "Bonliv"("REF_BL") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Facture" ADD CONSTRAINT "Facture_CODE_CLT_fkey" FOREIGN KEY ("CODE_CLT") REFERENCES "Client"("code_clt") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DetailFacture" ADD CONSTRAINT "DetailFacture_CODE_ART_fkey" FOREIGN KEY ("CODE_ART") REFERENCES "Article"("code_art") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DetailFacture" ADD CONSTRAINT "DetailFacture_REF_FAC_fkey" FOREIGN KEY ("REF_FAC") REFERENCES "Facture"("REF_FAC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Avoirs" ADD CONSTRAINT "Avoirs_CODE_CLT_fkey" FOREIGN KEY ("CODE_CLT") REFERENCES "Client"("code_clt") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Detailavoirs" ADD CONSTRAINT "Detailavoirs_CODE_ART_fkey" FOREIGN KEY ("CODE_ART") REFERENCES "Article"("code_art") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Detailavoirs" ADD CONSTRAINT "Detailavoirs_REF_AVR_fkey" FOREIGN KEY ("REF_AVR") REFERENCES "Avoirs"("REF_AVR") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reglement" ADD CONSTRAINT "Reglement_CODE_CLT_fkey" FOREIGN KEY ("CODE_CLT") REFERENCES "Client"("code_clt") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReglementDetail" ADD CONSTRAINT "ReglementDetail_REF_AV_FAC_fkey" FOREIGN KEY ("REF_AV_FAC") REFERENCES "UnifiedFactureAvoir"("REF_AV_FAC") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ReglementDetail" ADD CONSTRAINT "ReglementDetail_REF_REGV_fkey" FOREIGN KEY ("REF_REGV") REFERENCES "Reglement"("REF_REGV") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UnifiedFactureAvoir" ADD CONSTRAINT "UnifiedFactureAvoir_code_clt_fkey" FOREIGN KEY ("code_clt") REFERENCES "Client"("code_clt") ON DELETE RESTRICT ON UPDATE CASCADE;
